import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import CCircle from "@/public/social-media-icons/CCircle";
import Facebook from "@/public/social-media-icons/Facebook";
import Instagram from "@/public/social-media-icons/Instagram";
import Youtube from "@/public/social-media-icons/Youtube";
import TwitterX from "@/public/social-media-icons/TwitterX";
import Pinterest from "@/public/social-media-icons/Pinterest";
import LinkedIn from "@/public/social-media-icons/LinkedIn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FITOPIA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--background)] text-[var(--foreground)]`}
      >
        <header>
          <div className="flex flex-col w-full justify-center items-center">
            <div className="flex flex-row w-[90%] h-fit justify-between items-center p-8 mt-10 mb-16 shadow-xl rounded-3xl">
              <div className="flex flex-row justify-center items-center gap-4">
                <Link href={"/"}>
                  <Image
                    className="rounded-lg"
                    src="/fitopia-logo.png"
                    width={64}
                    height={64}
                    alt="Logo"
                  />
                </Link>
                <Link href={"/"} className="font-semibold text-lg">
                  FITOPIA-AI
                </Link>
              </div>
              <div className="flex flex-row justify-center items-center text-md gap-8">
                <Link className="font-semibold text-lg" href={"/"}>
                  Stores
                </Link>
                <Link className="font-semibold text-lg" href={"/"}>
                  Pricing
                </Link>
                <Link className="font-semibold text-lg" href={"/about"}>
                  About
                </Link>
              </div>
            </div>
          </div>
        </header>
        {children}
        <footer className="flex flex-col justify-center items-center pt-16">
          <div className="flex flex-col w-full min-h-fit justify-center items-center pt-8 pb-8">
            <div className="flex flex-col w-[90%] min-h-fit justify-center items-center gap-8">
              <div className="flex flex-row w-full min-h-fit justify-center items-center gap-8">
                <Link
                  className="font-normal text-sm hover:underline hover:underline-offset-4 transition-colors duration-200"
                  href={"/"}
                >
                  Stores
                </Link>
                <Link
                  className="font-normal text-sm hover:underline hover:underline-offset-4 transition-colors duration-200"
                  href={"/"}
                >
                  Pricing
                </Link>
                <Link
                  className="font-normal text-sm hover:underline hover:underline-offset-4 transition-colors duration-200"
                  href={"/about"}
                >
                  About
                </Link>
                <Link
                  className="font-normal text-sm hover:underline hover:underline-offset-4 transition-colors duration-200"
                  href={"/FAQ"}
                >
                  FAQ →
                </Link>
                <div className="flex flex-row justify-start items-center gap-1">
                  <CCircle />
                  <h1 className="font-normal text-sm">FITOPIA 2025</h1>
                </div>
              </div>
              <div className="flex flex-row w-full min-h-fit justify-center items-center gap-4">
                <Link href={"/"}>
                  <Facebook />
                </Link>
                <Link href={"/"}>
                  <Instagram />
                </Link>
                <Link href={"/"}>
                  <Youtube />
                </Link>
                <Link href={"/"}>
                  <TwitterX />
                </Link>
                <Link href={"/"}>
                  <Pinterest />
                </Link>
                <Link href={"/"}>
                  <LinkedIn />
                </Link>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
